apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-component-id  # Replace with actual component ID
  description: A sample description for the component  # Replace with actual description
  annotations:
    github.com/project-slug: owner/repo  # Replace with actual owner/repo
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: owner@example.com  # Replace with actual owner email
